### ISSUE TITLE
Error with MYSql 8

### ISSUE THREAD

**Issue by mordechaihorowitz** [juanmirocks/Levenshtein-MySQL-UDF#13]
When running GCC I get an error 

levenshtein.c:11:10: fatal error: my_global.h: No such file or directory
 #include <my_global.h>

**Comment by juanmirocks** [comment]
Thank you for the report.

Take a look at this: https://stackoverflow.com/questions/20909685/fatal-error-mysql-hno-such-file-or-directory-during-compilation
