### ISSUE TITLE
Can't find symbol 'levenshtein' in library

### ISSUE THREAD

**Issue by MIMAXUZ** [juanmirocks/Levenshtein-MySQL-UDF#17]
When I tried to create UDF it returns this message:
```
mysql> CREATE FUNCTION levenshtein RETURNS INT SONAME 'levenshtein.so';
ERROR 1127 (HY000): Can't find symbol 'levenshtein' in library
```
I tried with other names of function but no solution yet. 
Now my machine:
- Ubuntu 20.04
- MySQL 8.x
How can I fix it?
Thanks!

**Comment by juanmirocks** [comment]
Thanks for the report @MIMAXUZ 

Does any [workaround here](https://github.com/juanmirocks/Levenshtein-MySQL-UDF/issues/12) help you out?
