### ISSUE TITLE
compilation on macosX

### ISSUE THREAD

**Issue by peterhost** [juanmirocks/Levenshtein-MySQL-UDF#7]
Hi, just a suggestion

maybe replace : 

```
* (mac) gcc -bundle -o levenshtein.so levenshtein.c -I/usr/local/mysql/include
```

with

```
* (mac) gcc -bundle -o levenshtein.so levenshtein.c `mysql_config --cflags --libs`
```

As its more generic and works with whatever source you (properly) installed mysql with : oracle, homebrew, macports,...

And thanks for this implementation :)

**Comment by juanmirocks** [comment]
Thank you so much @peterhost ... 3 years and a half later... here: https://github.com/juanmirocks/Levenshtein-MySQL-UDF/commit/97d9e451f5f8480935a345df80afe99150948d9a 

🙈

THANKS ! 🐬
